import os

file_path = 'app/page.jsx'
with open(file_path, 'r', encoding='utf-8') as f:
    code = f.read()

# 1. Add UseEffect and copyAvg function
state_old = '''  const [history,setHistory]=useState(()=>{ try{return JSON.parse(localStorage.getItem("pivot_history")||"[]");}catch{return[];} });'''
state_new = '''  const [history,setHistory]=useState(()=>{ try{return JSON.parse(localStorage.getItem("pivot_history")||"[]");}catch{return[];} });

  useEffect(() => {
    if (tab === "avg" && avgEntries[0].price === "" && currentPrice) {
      setAvgEntries(e => { const n = [...e]; n[0].price = currentPrice; return n; });
    }
  }, [tab, avgEntries, currentPrice]);

  const copyAvg = () => {
    if(!avgResult) return;
    const sym = stockCode ? stockCode.toUpperCase() : "Saham";
    let diffText = "";
    if (currentPrice && !isNaN(parseFloat(currentPrice))) {
      const cp = parseFloat(currentPrice);
      const diff = (((avgResult.avgPrice - cp) / cp) * 100).toFixed(2);
      diffText = `\\nJarak ke Current Price: ${diff > 0 ? '+'+diff : diff}%`;
    }
    const text=`📉 *KALKULATOR AVERAGE DOWN*\\nEmiten: *${sym}*\\n━━━━━━━━━━━━━━━━\\n📦 Total Lot: ${fmtDec(avgResult.totalLot)} Lot\\n💰 Total Modal: Rp ${fmt(Math.round(avgResult.totalValue*100))}\\n🎯 *HARGA AVG BARU: ${fmtDec(avgResult.avgPrice)}*${diffText}\\n━━━━━━━━━━━━━━━━\\n*Generated by TradingStars Analyzer*`;
    navigator.clipboard.writeText(text); alert("✅ Hasil Kalkulasi Average Berhasil Disalin!");
  };
'''
code = code.replace(state_old, state_new)

# 2. Update Hitung Average Button
btn_old = '''<button onClick={hitungAvg} style={{ width:"100%",padding:"13px",background:"linear-gradient(135deg,#16a34a,#0891b2)",color:"#fff",border:"none",borderRadius:"10px",fontSize:"13px",fontWeight:800,cursor:"pointer",boxShadow:"0 4px 14px rgba(8,145,178,0.35)" }}>🧮 Hitung Average</button>'''
btn_new = '''<button onClick={hitungAvg} style={{ width:"100%",padding:"14px",background:"linear-gradient(135deg,#1d4ed8,#7c3aed)",color:"#fff",border:"none",borderRadius:"10px",fontSize:"14px",fontWeight:800,cursor:"pointer",boxShadow:"0 8px 24px rgba(124,58,237,0.35)",transition:"all 0.3s" }}>🧮 Hitung Average</button>'''
code = code.replace(btn_old, btn_new)

# 3. Add Distance indicator and Share Button to avgResult card
# Replace the HARGA RATA-RATA block
harga_old = '''                        <div style={{ fontSize:"11px",color:t.sub,marginBottom:"4px",fontWeight:600,letterSpacing:"1px" }}>HARGA RATA-RATA</div>
                        <div style={{ fontSize:"32px",fontWeight:900,color:"#2563eb",letterSpacing:"-1px",textShadow:"0 0 20px rgba(37,99,235,0.3)" }}><AnimNum value={avgResult.avgPrice} fmt={fmtDec} /></div>
                      </div>'''
harga_new = '''                        <div style={{ fontSize:"11px",color:t.sub,marginBottom:"4px",fontWeight:600,letterSpacing:"1px" }}>HARGA RATA-RATA</div>
                        <div style={{ fontSize:"32px",fontWeight:900,color:"#2563eb",letterSpacing:"-1px",textShadow:"0 0 20px rgba(37,99,235,0.3)" }}><AnimNum value={avgResult.avgPrice} fmt={fmtDec} /></div>
                        {currentPrice && !isNaN(parseFloat(currentPrice)) && (
                          <div style={{ fontSize:"11px",fontWeight:700,color:((avgResult.avgPrice - parseFloat(currentPrice))/parseFloat(currentPrice)) > 0 ? "#dc2626" : "#16a34a", marginTop:"6px", background:((avgResult.avgPrice - parseFloat(currentPrice))/parseFloat(currentPrice)) > 0 ? "rgba(220,38,38,0.1)" : "rgba(22,163,74,0.1)", padding:"4px 8px", borderRadius:"6px", display:"inline-block" }}>
                            {(((avgResult.avgPrice - parseFloat(currentPrice)) / parseFloat(currentPrice)) * 100).toFixed(2) > 0 ? "▲" : "▼"} Abs {Math.abs((((avgResult.avgPrice - parseFloat(currentPrice)) / parseFloat(currentPrice)) * 100).toFixed(2))}% dari Harga Saat Ini
                          </div>
                        )}
                      </div>'''
code = code.replace(harga_old, harga_new)

# 4. Share button at bottom
share_old = '''                        })}
                      </div>
                    </div>
                  </div>'''
share_new = '''                        })}
                      </div>
                      <button onClick={copyAvg} style={{ width:"100%",padding:"12px",marginTop:"16px",background:"#2563eb",color:"#fff",border:"none",borderRadius:"10px",fontSize:"13px",fontWeight:800,cursor:"pointer",boxShadow:"0 4px 14px rgba(37,99,235,0.35)" }}>📤 Salin & Share Kalkulasi</button>
                    </div>
                  </div>'''
code = code.replace(share_old, share_new)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(code)

print("Average enhancements successfully injected!")
