import os

file_path = 'app/page.jsx'
with open(file_path, 'r', encoding='utf-8') as f:
    code = f.read()

# 1. Update FadeIn animation
old_fade = '''function FadeIn({ children, delay=0, style={} }) {
  const ref = useRef(null);
  useEffect(() => {
    const el = ref.current; if (!el) return;
    el.style.opacity="0"; el.style.transform="translateY(10px)";
    const t = setTimeout(() => {
      el.style.transition=`opacity 0.4s ease ${delay}ms, transform 0.4s ease ${delay}ms`;
      el.style.opacity="1"; el.style.transform="translateY(0)";
    }, 30);
    return () => clearTimeout(t);
  }, [delay]);
  return <div ref={ref} style={style}>{children}</div>;
}'''

new_fade = '''function FadeIn({ children, delay=0, style={} }) {
  const ref = useRef(null);
  useEffect(() => {
    const el = ref.current; if (!el) return;
    el.style.opacity="0"; el.style.transform="translateY(30px)";
    const t = setTimeout(() => {
      el.style.transition=`opacity 0.6s cubic-bezier(0.22, 1, 0.36, 1) ${delay}ms, transform 0.6s cubic-bezier(0.22, 1, 0.36, 1) ${delay}ms`;
      el.style.opacity="1"; el.style.transform="translateY(0)";
    }, 30);
    return () => clearTimeout(t);
  }, [delay]);
  return <div ref={ref} style={style}>{children}</div>;
}

function getMarketStatus() {
  const d = new Date();
  const options = { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit', hour12: false };
  const str = d.toLocaleString('en-US', options);
  const parts = str.split(':');
  if (parts.length < 2) return "🟢 MARKET OPEN (Sesi 1) - Happy Cuan Stars! 🚀";
  const h = parseInt(parts[0], 10);
  const m = parseInt(parts[1], 10);
  const time = h * 60 + m;

  if (time >= 540 && time <= 720) return "🟢 MARKET OPEN (Sesi 1) - Happy Cuan Stars! 🚀";
  if (time >= 810 && time <= 960) return "🟢 MARKET OPEN (Sesi 2) - Pantau Bandar Power! 🐋";
  return "🔴 MARKET CLOSED - Siapkan Analisa Besok! 📈";
}'''
code = code.replace(old_fade, new_fade)

# 2. Update copyAnalisa
old_copy = '''  const copyAnalisa=()=>{
    if(!result) return;
    const s=getSentiment();
    const text=`📊 PIVOT POINT ANALISA\\n━━━━━━━━━━━━━━━━\\nR3: ${fmt(result.r3)}\\nR2: ${fmt(result.r2)}\\nR1: ${fmt(result.r1)}\\nPP: ${fmt(result.pivot)}\\nS1: ${fmt(result.s1)}\\nS2: ${fmt(result.s2)}\\nS3: ${fmt(result.s3)}\\n━━━━━━━━━━━━━━━━\\n${s?`Sentiment: ${s.label}\\n`:""}📈 NAIK: ${fmt(result.pivot)} → ${fmt(result.r1)} → ${fmt(result.r2)} → ${fmt(result.r3)}\\n📉 TURUN: ${fmt(result.pivot)} → ${fmt(result.s1)} → ${fmt(result.s2)} → ${fmt(result.s3)}\\n\\n#PivotPoint #Trading #IDX`;
    navigator.clipboard.writeText(text); setCopied(true); setTimeout(()=>setCopied(false),2500);
  };'''

new_copy = '''  const copyAnalisa=()=>{
    if(!result) return;
    const sym = stockCode ? stockCode.toUpperCase() : "IHSG/Saham";
    let statusText = "Normal (Volume/MA20 kosong)";
    if (bandarPower) statusText = bandarPower.status;

    let rrText = "Belum diset (Isi Equity/Risk)";
    const eq = parseFloat(equity);
    const risk = parseFloat(riskPct);
    const cp = parseFloat(currentPrice) || result.pivot;
    
    if (!isNaN(eq) && !isNaN(risk) && eq > 0 && risk > 0 && cp > result.s1) {
      const maxLossRp = eq * (risk / 100);
      const lossPerShare = cp - result.s1;
      const maxShares = maxLossRp / lossPerShare;
      const lotSize = Math.floor(maxShares / 100);
      if (lotSize > 0) {
        const actualRisk = (lotSize * 100) * lossPerShare;
        const potentialProfit = (lotSize * 100) * (result.r1 - cp);
        if (potentialProfit > 0) rrText = `1 : ${(potentialProfit / actualRisk).toFixed(2)}`;
      }
    }

    const text=`📊 *TRADING STARS - PIVOT REPORT*\\nEmiten: *${sym}*\\n--------------------------\\n📈 *Pivot Point:* ${fmt(result.pivot)}\\n🚀 *Resist:* ${fmt(result.r1)} | ${fmt(result.r2)}\\n🛡️ *Support:* ${fmt(result.s1)} | ${fmt(result.s2)}\\n⚡ *Bandar Power:* ${statusText}\\n⚖️ *R/R Ratio:* ${rrText}\\n--------------------------\\n*Generated by TradingStars Analyzer*`;
    navigator.clipboard.writeText(text); setCopied(true); setTimeout(()=>setCopied(false),2500);
  };'''
code = code.replace(old_copy, new_copy)

# 3. Marquee placement inside wrapper
old_wrapper_start = '''<div className={`min-h-screen flex justify-center p-6 relative transition-colors duration-500 ${dark ? "bg-gradient-to-br from-slate-900 to-black text-white" : "bg-white text-black"}`} style={{ fontFamily:"'Segoe UI',system-ui,sans-serif" }}>'''
new_wrapper_start = '''<div className={`min-h-screen flex justify-center p-6 relative transition-colors duration-500 ${dark ? "bg-gradient-to-br from-slate-900 to-black text-white" : "bg-white text-black"}`} style={{ fontFamily:"'Segoe UI',system-ui,sans-serif", paddingTop: "50px" }}>
      <div style={{ position: "absolute", top: 0, left: 0, width: "100%", padding: "8px 0", background: dark ? "rgba(0,0,0,0.6)" : "rgba(226,232,240,0.8)", backdropFilter: "blur(4px)", borderBottom: `1px solid ${dark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.05)"}`, zIndex: 10 }}>
        <marquee scrollamount="5" style={{ fontSize: "11px", fontWeight: 800, letterSpacing: "1px", color: dark ? "#f8fafc" : "#1e293b" }}>{getMarketStatus()}</marquee>
      </div>'''
code = code.replace(old_wrapper_start, new_wrapper_start)

# 4. Button label change
old_button = '''{copied ? "✅ Berhasil Disalin!" : "📋 Copy Analisa"}'''
new_button = '''{copied ? "✅ Laporan Disalin!" : "📤 Salin & Share Analisa"}'''
code = code.replace(old_button, new_button)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(code)

print("Replacement done for 3 premium features.")
