import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { verifySession, readSessionCookie } from "../../../utils/auth";

// Runs server-side only — the Gemini API key never reaches the browser.
export const runtime = "nodejs";

const MODEL = process.env.GEMINI_MODEL || "gemini-2.5-flash";

// Fixed, server-controlled disclaimer (not generated by the model).
const DISCLAIMER =
  "⚠️ Analisa AI ini bersifat edukatif, BUKAN nasihat finansial. Pasar berisiko — keputusan jual/beli sepenuhnya tanggung jawab Anda.";

export async function POST(req: Request) {
  // Proteksi: di production wajib sudah login (punya cookie session) supaya
  // endpoint tidak bisa di-spam publik & menghabiskan kuota/biaya Gemini.
  // Dev tetap bebas biar gampang dites lokal.
  if (process.env.NODE_ENV === "production") {
    const token = readSessionCookie(req.headers.get("cookie"));
    const ok = await verifySession(token, process.env.JWT_SECRET);
    if (!ok) {
      return NextResponse.json(
        { ok: false, error: "Akses ditolak. Silakan login dulu." },
        { status: 401 }
      );
    }
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { ok: false, error: "GEMINI_API_KEY belum diset di .env.local" },
      { status: 500 }
    );
  }

  let body: any;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Body JSON tidak valid" }, { status: 400 });
  }

  const { stockCode, timeframe, ohlc, pivots, currentPrice, pattern, confluence, rrr } = body || {};
  if (!ohlc || !pivots) {
    return NextResponse.json(
      { ok: false, error: "Data ohlc & pivots wajib dikirim" },
      { status: 400 }
    );
  }

  // Konteks tambahan yang sudah dihitung app (pola candle, confluence, RRR)
  const ctx = [
    pattern ? `Pola candle terdeteksi: ${pattern}` : null,
    confluence ? `Confluence: ${confluence}` : null,
    rrr ? `Risk/Reward ratio (app): ${rrr}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const prompt = `Kamu adalah analis teknikal saham IDX yang objektif dan ringkas. Analisis data berikut dalam Bahasa Indonesia.

Emiten: ${stockCode || "-"}
Timeframe: ${timeframe || "DAILY"}
OHLC: Open ${ohlc.open ?? "-"}, High ${ohlc.high}, Low ${ohlc.low}, Close ${ohlc.close}
Harga saat ini: ${currentPrice ?? ohlc.close}
Volume: ${ohlc.volume ?? "-"} (MA20 Volume: ${ohlc.ma20Volume ?? "-"})
MA20 Price: ${ohlc.ma20Price ?? "-"}
Pivot Point: PP ${pivots.PP} | Resistance R1 ${pivots.R1} R2 ${pivots.R2} R3 ${pivots.R3} | Support S1 ${pivots.S1} S2 ${pivots.S2} S3 ${pivots.S3}
${ctx ? ctx + "\n" : ""}
Balas HANYA dengan JSON valid (tanpa teks lain), struktur:
{"sentiment":"BULLISH|BEARISH|NETRAL","confidence":<angka 0-100, tingkat keyakinan analisa>,"headline":"ringkasan 1 kalimat","analysis":"2-4 kalimat analisa teknikal","keyLevels":"level support/resistance penting yang dipantau","entry":"area harga entry yang disarankan","tp":"target profit (boleh lebih dari satu, pisah koma)","sl":"level stop loss","risk":"1 kalimat catatan risiko utama"}`;

  try {
    const ai = new GoogleGenAI({ apiKey });
    const callGemini = async () => {
      const res = await ai.models.generateContent({
        model: MODEL,
        contents: prompt,
        config: {
          temperature: 0.6,
          maxOutputTokens: 1024,
          responseMimeType: "application/json",
          // gemini-2.5-flash mengaktifkan "thinking" by default yang memakan
          // jatah maxOutputTokens hingga JSON terpotong. Matikan untuk tugas
          // ekstraksi terstruktur ini (lebih cepat & murah, output utuh).
          thinkingConfig: { thinkingBudget: 0 },
        },
      });
      return (res.text || "").trim();
    };

    let text = "";
    try {
      text = await callGemini();
    } catch (e: any) {
      // Retry sekali untuk error transient (model overload / 503).
      if (!/503|UNAVAILABLE|overload|high demand/i.test(e?.message || "")) throw e;
      await new Promise((r) => setTimeout(r, 1200));
      text = await callGemini();
    }
    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch {
      // Model returned non-JSON — surface the raw text rather than failing.
      parsed = { sentiment: "NETRAL", headline: "Ringkasan", analysis: text };
    }

    return NextResponse.json({
      ok: true,
      model: MODEL,
      analysis: { ...parsed, disclaimer: DISCLAIMER },
    });
  } catch (err: any) {
    // Pesan error @google/genai sering berupa string JSON — ambil pesan manusiawinya.
    let msg = err?.message || "Gagal memanggil Gemini";
    try {
      const m = JSON.parse(msg);
      if (m?.error?.message) msg = m.error.message;
    } catch {}
    if (/503|UNAVAILABLE|overload|high demand/i.test(msg)) {
      msg = "Model Gemini sedang sibuk. Coba lagi sebentar lagi.";
    } else if (/429|quota|RESOURCE_EXHAUSTED|rate limit/i.test(msg)) {
      msg = "Kuota Gemini tercapai. Tunggu sebentar lalu coba lagi (cek limit di Google AI Studio).";
    }
    return NextResponse.json({ ok: false, error: msg }, { status: 502 });
  }
}
