import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { verifySession, readSessionCookie } from "../../../utils/auth";

// Runs server-side only — the Gemini API key never reaches the browser.
export const runtime = "nodejs";

const MODEL = process.env.GEMINI_MODEL || "gemini-2.5-flash";

// Fixed, server-controlled disclaimer (not generated by the model).
const DISCLAIMER =
  "⚠️ Analisa AI ini bersifat edukatif, BUKAN nasihat finansial. Pasar berisiko — keputusan jual/beli sepenuhnya tanggung jawab Anda.";

// ── Confluence Score (sumber kebenaran = backend, BUKAN Gemini) ─────────────
// Gemini hanya analisa kualitatif (sentiment). Skor dihitung deterministik di sini.
type SmcSignal = "STRONG" | "MODERATE" | "WEAK";

// Derive kekuatan SMC dari indikator teknikal (struktur, tren, volume, breakout).
function deriveSmcSignal(ohlc: any, pivots: any, currentPrice: any): SmcSignal {
  const cp = Number(currentPrice ?? ohlc?.close);
  const ma20 = Number(ohlc?.ma20Price);
  const vol = Number(ohlc?.volume);
  const volMa = Number(ohlc?.ma20Volume);
  const open = Number(ohlc?.open);
  const close = Number(ohlc?.close);
  let n = 0;
  if (Number.isFinite(cp) && Number.isFinite(pivots?.PP) && cp > pivots.PP) n++; // struktur bullish (BoS)
  if (Number.isFinite(cp) && Number.isFinite(ma20) && cp > ma20) n++;            // tren di atas MA20
  if (Number.isFinite(vol) && Number.isFinite(volMa) && vol > volMa) n++;        // konfirmasi volume / liquidity
  if (Number.isFinite(cp) && Number.isFinite(pivots?.R1) && cp >= pivots.R1) n++;// breakout R1 (liquidity sweep)
  if (Number.isFinite(close) && Number.isFinite(open) && close > open) n++;      // candle bullish (ChoCh-ish)
  if (n >= 4) return "STRONG";
  if (n >= 2) return "MODERATE";
  return "WEAK";
}

// Skor 0-100: Trend(+20) Volume(+20) Sentiment(+30) SMC(+30).
function computeConfluence(ohlc: any, pivots: any, currentPrice: any, sentiment: any) {
  const cp = Number(currentPrice ?? ohlc?.close);
  const ma20 = Number(ohlc?.ma20Price);
  const vol = Number(ohlc?.volume);
  const volMa = Number(ohlc?.ma20Volume);
  const smc = deriveSmcSignal(ohlc, pivots, currentPrice);
  let score = 0;
  if (Number.isFinite(cp) && Number.isFinite(ma20) && cp > ma20) score += 20;
  if (Number.isFinite(vol) && Number.isFinite(volMa) && vol > volMa) score += 20;
  const s = String(sentiment ?? "").toUpperCase();
  if (s.includes("BULLISH")) score += 30;
  else if (s.includes("KONSOLIDASI")) score += 15;
  if (smc === "STRONG") score += 30;
  else if (smc === "MODERATE") score += 15;
  return { confluence_score: Math.min(score, 100), smc_signal: smc };
}

function confidenceLabel(score: number): string {
  if (score <= 20) return "Very Weak";
  if (score <= 40) return "Weak";
  if (score <= 60) return "Neutral";
  if (score <= 80) return "Strong";
  return "Very Strong";
}

export async function POST(req: Request) {
  // Proteksi: di production wajib sudah login (punya cookie session) supaya
  // endpoint tidak bisa di-spam publik & menghabiskan kuota/biaya Gemini.
  // Dev tetap bebas biar gampang dites lokal.
  if (process.env.NODE_ENV === "production") {
    const token = readSessionCookie(req.headers.get("cookie"));
    const ok = await verifySession(token, process.env.JWT_SECRET);
    if (!ok) {
      return NextResponse.json(
        { ok: false, error: "Akses ditolak. Silakan login dulu." },
        { status: 401 }
      );
    }
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { ok: false, error: "GEMINI_API_KEY belum diset di .env.local" },
      { status: 500 }
    );
  }

  let body: any;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Body JSON tidak valid" }, { status: 400 });
  }

  const { stockCode, timeframe, ohlc, pivots, currentPrice, pattern, confluence, rrr } = body || {};
  if (!ohlc || !pivots) {
    return NextResponse.json(
      { ok: false, error: "Data ohlc & pivots wajib dikirim" },
      { status: 400 }
    );
  }

  // Konteks tambahan yang sudah dihitung app (pola candle, confluence, RRR)
  const ctx = [
    pattern ? `Pola candle terdeteksi: ${pattern}` : null,
    confluence ? `Confluence: ${confluence}` : null,
    rrr ? `Risk/Reward ratio (app): ${rrr}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const prompt = `Kamu adalah analis teknikal saham IDX yang objektif dan ringkas. Analisis data berikut dalam Bahasa Indonesia.

Emiten: ${stockCode || "-"}
Timeframe: ${timeframe || "DAILY"}
OHLC: Open ${ohlc.open ?? "-"}, High ${ohlc.high}, Low ${ohlc.low}, Close ${ohlc.close}
Harga saat ini: ${currentPrice ?? ohlc.close}
Volume: ${ohlc.volume ?? "-"} (MA20 Volume: ${ohlc.ma20Volume ?? "-"})
MA20 Price: ${ohlc.ma20Price ?? "-"}
Pivot Point: PP ${pivots.PP} | Resistance R1 ${pivots.R1} R2 ${pivots.R2} R3 ${pivots.R3} | Support S1 ${pivots.S1} S2 ${pivots.S2} S3 ${pivots.S3}
${ctx ? ctx + "\n" : ""}
Balas HANYA dengan JSON valid (tanpa teks/markdown lain), struktur PERSIS:
{"sentiment":"BULLISH|BEARISH|KONSOLIDASI|wait_and_see","headline":"ringkasan 1 kalimat","entry":{"agresif":{"level":<angka harga atau "N/A">,"desc":"alasan singkat, mis. breakout R1"},"demand":{"level":<angka harga atau "N/A">,"desc":"alasan singkat, mis. batas bawah area demand/support"}},"tp":{"level":<angka harga atau "N/A">,"reason":"alasan teknikal target ini"},"sl":{"level":<angka harga atau "N/A">,"reason":"alasan teknikal, mis. di bawah MA20/S1"},"analysis_text":"narasi analisa teknikal 2-4 kalimat; pisahkan poin dengan \\n bila perlu","zona_pantau":{"bottom":<angka harga>,"top":<angka harga>,"desc":"deskripsi singkat area pantau"},"keyLevels":"level kunci yang dipantau","risk":"1 kalimat catatan risiko utama"}
ATURAN:
- Jika sentiment "BEARISH" atau "wait_and_see": set SEMUA level entry/tp/sl ke "N/A", dan WAJIB isi zona_pantau dengan area SUPPORT TERKUAT di bawah harga saat ini tempat trader bersiap memantau potensi rebound (bottom < top).
- Jika "BULLISH"/"KONSOLIDASI": zona_pantau boleh area demand terdekat sebagai zona re-entry.
- Narasi analysis_text harus profesional, edukatif, ringkas, dan menyebut istilah teknikal relevan secara natural: SMC, Break of Structure (BoS), Change of Character (ChoCh), Liquidity, Order Block, VCP.
- JANGAN menghitung skor confluence — kamu hanya melakukan analisa kualitatif.`;

  try {
    const ai = new GoogleGenAI({ apiKey });
    const callGemini = async () => {
      const res = await ai.models.generateContent({
        model: MODEL,
        contents: prompt,
        config: {
          temperature: 0.6,
          maxOutputTokens: 1024,
          responseMimeType: "application/json",
          // gemini-2.5-flash mengaktifkan "thinking" by default yang memakan
          // jatah maxOutputTokens hingga JSON terpotong. Matikan untuk tugas
          // ekstraksi terstruktur ini (lebih cepat & murah, output utuh).
          thinkingConfig: { thinkingBudget: 0 },
        },
      });
      return (res.text || "").trim();
    };

    let text = "";
    try {
      text = await callGemini();
    } catch (e: any) {
      // Retry sekali untuk error transient (model overload / 503).
      if (!/503|UNAVAILABLE|overload|high demand/i.test(e?.message || "")) throw e;
      await new Promise((r) => setTimeout(r, 1200));
      text = await callGemini();
    }
    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch {
      // Model returned non-JSON — surface the raw text rather than failing.
      parsed = { sentiment: "NETRAL", headline: "Ringkasan", analysis: text };
    }

    // Confluence Score dihitung di server (sumber kebenaran), bukan dari Gemini.
    const { confluence_score, smc_signal } = computeConfluence(ohlc, pivots, currentPrice, parsed?.sentiment);

    return NextResponse.json({
      ok: true,
      model: MODEL,
      analysis: {
        ...parsed,
        disclaimer: DISCLAIMER,
        confluence_score,
        confidence: confidenceLabel(confluence_score),
        smc_signal,
      },
    });
  } catch (err: any) {
    // Pesan error @google/genai sering berupa string JSON — ambil pesan manusiawinya.
    let msg = err?.message || "Gagal memanggil Gemini";
    try {
      const m = JSON.parse(msg);
      if (m?.error?.message) msg = m.error.message;
    } catch {}
    if (/503|UNAVAILABLE|overload|high demand/i.test(msg)) {
      msg = "Model Gemini sedang sibuk. Coba lagi sebentar lagi.";
    } else if (/429|quota|RESOURCE_EXHAUSTED|rate limit/i.test(msg)) {
      msg = "Kuota Gemini tercapai. Tunggu sebentar lalu coba lagi (cek limit di Google AI Studio).";
    }
    return NextResponse.json({ ok: false, error: msg }, { status: 502 });
  }
}
